version: '2'
services:
  traefik:
    image: traefik:1.5.4
    restart: always
    ports:
      - "80:80"
    networks:
      - dash-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    container_name: traefik
networks:
  dash-net:
    external: true
