version: '2'
services:
  traefik:
    image: traefik:1.7.4-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - dash-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./ssl:/ssl
    container_name: traefik
  dash-portainer:
    image: portainer/portainer
    networks:
      - dash-net
    restart: always
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/dash-portainer/"
      - "traefik.enable=true"
      - "traefik.docker.network=dash-net"
      - "traefik.port=9000"
      - "traefik.backend=portainer"
    container_name: dash-portainer
networks:
  dash-net:
    external: true
volumes:
  portainer-data:
    external: true
