debug = false

logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]
	
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    certFile = "ssl/traefik.crt"
    keyFile = "ssl/traefik.key"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "speedegree.tk"
watch = true
exposedByDefault = false
