debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http"]
	
[entryPoints]
  [entrtPoints.http]
  address = ":80"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "dev-maristdash.tk"
watch = true
exposedByDefault = false
