debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]
	
[entryPoints]
  [entrtPoints.http]
	address = ":80"
	  [entryPoints.http]
	[entrypoints.https]
	address = ":443"
	  [entryPoints.https.redirect]
	  entryPoint = "http"
	  

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "dev-maristdash.tk"
watch = true
exposedByDefault = false